### ISSUE TITLE
Gradle 6.0.1 java.lang.NoSuchFieldException: entryTasks

### ISSUE THREAD

**Issue by aeiplatform** [mmalohlava/gradle-visteg#18]
```
plugins {
    id("cz.malohlava.visteg") version "1.0.5"
}
```

> Exception is:
org.gradle.internal.event.ListenerNotificationException: Failed to notify task execution graph listener.
Caused by: java.lang.NoSuchFieldException: entryTasks
	at java_lang_Class$getDeclaredField.call(Unknown Source)
	at cz.malohlava.VisTaskExecGraphPlugin.getEntryTasks(VisTaskExecGraphPlugin.groovy:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at cz.malohlava.VisTaskExecGraphPlugin$_apply_closure2.doCall(VisTaskExecGraphPlugin.groovy:85)

**Comment by bellini-ea** [comment]
To help with this, I found it occurring when upgrading to gradle 6.0.1 from 5.6

`Cause 1: java.lang.NoSuchFieldException: entryTasks
        at java_lang_Class$getDeclaredField.call(Unknown Source)
        at cz.malohlava.VisTaskExecGraphPlugin.getEntryTasks(VisTaskExecGraphPlugin.groovy:134).`  

Same version as the other person mentioned:
`id("cz.malohlava.visteg") version "1.0.5"`

**Comment by umayrh** [comment]
Same error. Gradle version is 6.0.1

**Comment by mmalohlava** [comment]
The proposed fix is in https://github.com/mmalohlava/gradle-visteg/pull/22

Not the perfect fix since it will break older version of Gradle. But at least unblock usage of plugin in Gradle v6+
